### PR TITLE
(De)serializable ConfigBuilder

### PR DESCRIPTION
**Pull request by monoid**
Derive Serializable and Deserializable for async_raft::config::ConfigBuilder and async_raft::config::SnapshotPolicy for users' convenience.

### CODE REVIEW

**Comment by monoid** [comment]
This is intended for simpler config definition.  One can add `async_raft::config::Config` field to his config and deserialize it with serde_yaml, for example.  The only thing that concerns me is `snapshot_policy` serde enum representation.  However, default behavior seems to be both convenient for configs and future-proof.

**Comment by monoid** [comment]
Upd: it seems that for sake of configuration, deserializing ConfigBuilder is much better.

**Review by thedodd — CHANGES_REQUESTED** [review]
Hey @monoid I do think that you probably want the derives to be on the `Config` struct itself, not the builder. The builder is really only used for programmatically building a config instance. Deriving on the `Config` struct (and the `SnapshotPolicy` as well, which is good) will allow you to store a serialized form of the config as JSON, YAML, TOML whatever and your app can deal with it that way. 

If you have a good use case for deriving on the builder too, that's fine, keep it (just let me know because I'm curious), but let's definitely derive directly on the `Config` struct as well.

Thoughts?

**Comment by monoid** [comment]
It certainly wouldn't hurt to make `Config` (de)serializable as well.  I've pushed the new version. The use case for deserializable `ConfigBuilder` is here:

```rust
use std::error::Error;
use std::fs::File;
use serde::Deserialize;
use serde_yaml;
    
#[derive(Deserialize)]
struct AppConfig {
    /// Client HTTP port
    http_port: u16,
    /// RAFT port for cluster intercommunication
    raft_port: u16,

    raft_config: async_raft::ConfigBuilder,
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut file = File::open("conf.yaml")?;
    let app_conf: AppConfig = serde_yaml::from_reader(&mut file)?;

    eprintln!(
        "HTTP port: {}, RAFT port: {}",
        app_conf.http_port, app_conf.raft_port
    );
    // Get final Raft config with defaults filled in.
    let raft_config = app_conf.raft_config.validate()?;
    eprintln!("Raft config: {:?}", raft_config);
    Ok(())
}

/*
Example conf.yaml where some optional fields are omitted:

http_port: 8000
raft_port: 7000

raft_config:
    cluster_name: "test"
    max_payload_entries: 150
    snapshot_policy:
            LogsSinceLast: 500

*/
```

Using `ConfigBuilder` for user config has to big pluses: 1. One can omit optional fields; 2. Values are validated.

**Review by thedodd — APPROVED** [review]
+1 this looks really great. @monoid do you mind updating the changelog with a line describing these changes?

**Comment by thedodd** [comment]
No worries. Once CI passes, I'll merge and update changelog so that I can get a release out ASAP.

**Comment by monoid** [comment]
Oh, I've already wrote a changelog statement :)

However, I have one more question: as one deserializes `ConfigBuilder`, he needs to know its fields.  But the `cluster_name` is private and is not listed in the documentation, and it is not optional either.  So I suggest to make it public, it seems there no harm in it.

**Comment by thedodd** [comment]
@monoid cool. I'll go ahead and merge this now. I'll update the changelog as well. 

Also, I'll go ahead and make the cluster name field public on the builder. I had not considered your use case before, however it is definitely valid. Being able to leverage the validation that you get with the builder is definitely a big win.

Thanks for putting this together!!! Also, if you are inclined to share, what sort of system are you hacking on?

**Comment by monoid** [comment]
Yoo-hoo!!!

So far I'm just wrapping my head around Raft and `async-raft`, trying to write toy system with file storage and network communication.

**Pull request merged**
