### PR TITLE
Upgrade to actix-0.9

### PR DESCRIPTION
**Pull request by Diggsey**
This is still WIP. It's compiling, but it's failing the tests and I haven't tracked down the issue yet.

### CODE REVIEW

**Comment by Diggsey** [comment]
The translation was fairly mechanical, and I haven't really tried to improve the resulting code to use the newer constructs yet.

The biggest issue I had was that the set of combinators provided by actix (and even futures in some cases) are completely inadequate, so I had to reimplement some of them in the `try_fut` module.

**Comment by Diggsey** [comment]
I tracked down the problem to a bug in actix-0.9's StreamThen combinator. What was I saying about inadequate combinators...

**Comment by thedodd** [comment]
@Diggsey excellent work on this so far. Keep me posted. Looks like `StreamThen` issue has been resolved.

**Comment by Diggsey** [comment]
@thedodd Yeah, but the fix is only in the 0.10.x pre-release, it hasn't been back-ported to 0.9.

I have another option: I recently released a crate [`actix-interop`](https://docs.rs/actix-interop/0.1.0/actix_interop/) which allows using async/await and normal futures with actix. Basically you don't need to work with the ActorFuture trait at all anymore. As well as async/await you get the full suite of futures-rs combinators.

Is that an option you would consider using?

**Comment by GopherJ** [comment]
Hello, I'm also interested in this PR, @Diggsey any idea on why it fails? Is it because of the new module: `try_fut`?

**Comment by thedodd** [comment]
Looking at the test failures:
- tests are failing in the `client_writes` integration test module.
- the receiver for handling client responses is closing prematurely. 

I'm hoping to have a lot more time here soon. Once my current workload clears-up, I'll be able to re-engage here. I'm actually planning on open-sourcing the original project which this was created for (Railgun). Sorry for the test of patience folks `:)`.

**Comment by Diggsey** [comment]
@GopherJ yeah if you check the previous messages in this thread I tracked down the problem earlier and reported is as a bug in actix - this bug was fixed upstream, but the fix was not back-ported to actix-0.9 (actix-0.10 is not released yet).

The bug was in the implementation of one of the ActorFuture combinators: my suggestion is to stop using ActorFuture combinators entirely (they are more limited and clearly less well tested), and instead use async/await and the normal future combinators, but this is only possible using my crate actix-interop.

This is why I am keen to hear back from @thedodd as to whether he would be comfortable in taking this approach. If not, the alternatives are to either:
1) Try to get the fix back-ported to actix-0.9
2) Wait until actix-0.10 is released
3) Switch to using the actix-0.10 pre-release
4) Use a custom fork of actix-0.9

**Comment by GopherJ** [comment]
@Diggsey @thedodd Hi guys, will it be possible to have this recently?

**Comment by thedodd** [comment]
@Diggsey hey, so I'm thinking that the logical thing to do would be to go ahead and update to actix `0.10.0-alpha.3`. We can always issue an alpha release of this crate with some info in the readme that we will cut an official release once actix `0.10` lands. Should be pretty reasonable.

@GopherJ && @Diggsey thoughts?

**Comment by GopherJ** [comment]
@thedodd pre-release is fine for me. At the same time a pre-release of `actix-raft` can also be used.

**Comment by raultang** [comment]
@thedodd I have continued work on @Diggsey 's PR 

- Upgrade `actix` to `0.10.0-alpha.3`
- Upgrade `pin-utils` to stable release
- All tests are passing.  
- Merged latest changes of `actix-raft`

https://github.com/raultang/actix-raft/tree/actix-0.10.0-alpha.3
So should I summit a PR?

@Diggsey I am thinking of the `try_fut` module, maybe we can summit to actix project, let community to review and stabilize it as there should others need it.  
https://github.com/actix/actix/issues/314

**Comment by GopherJ** [comment]
@raultang  It's a good idea to submmit that module to actix

**Comment by raultang** [comment]
@GopherJ FYI, I see `TryFutureExt ` for `ActorFuture` was add to actix 0.10 roadmap.

**Comment by thedodd** [comment]
Hey folks, just wanted to drop the word here that I'm making some really great progress on a major update to this crate, per some discussions a few of us have had around the repo.
- moves off of actix entirely. 
- squarely based on tokio (though adding support for async-std and other runtimes in the future will definitely be an option).
- I'm VERY happy with the amount of code I've been able to remove and simplify due to async/await.
- lots of other stuff. Hopefully I'll have the PR open shortly.

**Comment by thedodd** [comment]
@raultang @GopherJ @Diggsey the work done in #59 should address all of the items discussed here. Gonna tag this with `disposition:close`. @Diggsey def let me know if you think there is anything missing. You've been immensely helpful in identifying a few issues with the `0.4` version, thank you!

**Pull request closed without merging**
