### PR TITLE
Avoid requiring Debug bound for AppData and AppDataResponse

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by thedodd** [comment]
@xu-cheng thanks for the PR! I'll get this reviewed ASAP. If all is g2g, we can probably get this rolled out as part of the `0.5.6` release.

**Comment by thedodd** [comment]
@xu-cheng I updated your branch with a merge from master. Looks like the branch is causing some clippy errors. Mind updating? Once all of that is green, we can merge and release.

**Comment by xu-cheng** [comment]
The reason it failed before is because the `tracing::instrument` requires `Debug` bound for AppData. I have updated the PR to exclude `entries: Vec<Entry<D>>` from the the `tracing::instrument` inputs.

**Comment by thedodd** [comment]
Bringing this guy up-to-date then will merge.

**Pull request merged**
