### PR TITLE
Update Tokio to 1.0

### PR DESCRIPTION
**Pull request by xu-cheng**
~~Also use `futures::channel::{mpsc, oneshot}` instead of
`tokio::sync::{mpsc, oneshot}` for two reasons:~~

* ~~`try_recv()` was removed from `mpsc` types in Tokio.
  See https://github.com/tokio-rs/tokio/pull/3263~~
* ~~This would help us to make this library runtime agnostic in the future.~~

### CODE REVIEW

**Comment by thedodd** [comment]
Hello @xu-cheng! Thanks for all of the work you've been submitting recently. I've started the review process here, and should have time to finish it up tomorrow. Just as a heads-up, there are a few things which I would like to modify with the changeset here. Primarily, I don't want to focus on making changes to remove the centrality of Tokio from this crate quite yet. I still want to be runtime agnostic long-term, but not quite yet. My reasoning:
- I have a few ergonomics changes in flight right now which will constitute a breaking change (definitely for the better).
- Getting Tokio 1.0 compat will be a big win, let's just take that win as is and bake it in as part of the next release.
- I'm a bit concerned about moving off of the tokio implementation of various channel types. The Tokio team has done a great deal of optimization and tuning on their implementations, and I don't want to take an unnecessary performance hit for no reason.
- I would like to have the runtime agnostic effort as an isolated task which we can plan for and discuss. For now, Tokio is by far the best option.

Once again, thanks for the code! I'll circle back tomorrow with line items.

**Review by thedodd — CHANGES_REQUESTED** [review]
Ok, I've highlighted all of the areas where I would like for us to revert back to the standard Tokio implementation instead of using the futures crate. All comments are the same, I just added the text `″` (double prime, aka ditto).

I did not highlight every single location as I think that would be pedantic `:)`; however, once you make the changes to the `use` statements to cut them back over to Tokio, the compiler should do the rest to guide making the remaining updates. Seems like it will be mostly removing the `.await` statements on a fair number of unbounded send calls, as they are not async in the tokio impl.

Ping me once you are happy with the changes. Happy New Year!

**Comment by xu-cheng** [comment]
> Ok, I've highlighted all of the areas where I would like for us to revert back to the standard Tokio implementation instead of using the futures crate

There is one issue. `try_recv()` has been removed from mpsc type in Tokio (See tokio-rs/tokio#3263). So it means we need at least to change some mpsc types to futures' implementation. Thus, we will have mixed use of both Tokio and futures mpsc types. Is this OK? If so, I will update PR.

**Comment by xu-cheng** [comment]
Never mind, I just found out this https://github.com/tokio-rs/tokio/issues/3350#issue-774853870

**Comment by xu-cheng** [comment]
Ping @thedodd, any chance to merge this PR along with a few of others?

**Comment by neithanmo** [comment]
Any updates on this regard?? I have a dependency mismatch because I am using tokio 1.x with other libraries and this one that uses tokio 0.2, and I am facing problems with internal async-raft functions that call tokio::spawn, generating a panic:
```
panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`
```

**Comment by xu-cheng** [comment]
Updated PR to fix the merge conflict.

**Comment by thedodd** [comment]
@neithanmo this PR is next on my list. We should have it merged soon. My plan is to have it go out as part of the `0.6.0` release, which is currently in alpha.

**Comment by neithanmo** [comment]
> @neithanmo this PR is next on my list. We should have it merged soon. My plan is to have it go out as part of the `0.6.0` release, which is currently in alpha.
Great!!!.  I will update it, As soon as it landed to version 0.6.0
thanks.

**Comment by xu-cheng** [comment]
Updated PR to include the recent changes.

**Review by thedodd — APPROVED** [review]
+1 let's do this!

**Pull request merged**
