### PR TITLE
fix: a NonVoter should stay as NonVoter instead of Follower after restart

### PR DESCRIPTION
**Pull request by drmingdrmer**
# Summary

When restarting a NonVoter node with some log, the raft State initialization makes a NonVoter node a Follower node:
https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/mod.rs#L187-L223

Which lets a NonVoter has a chance to elect itself.

# Reproduce

- Start node 0 and node 1 with an empty store.
- Initialize node 0 with a cluster with only itself in it.
- Call `add_non_voter(1)` on node 0 to let it forward logs to node 1.
- Write a log and commit it. Now both node 0 and node 1 have the written log.
- Shut down both. Then restart node 1(the NonVoter) with the populated store.
- Then node 1 becomes a Follower.

Detailed steps are in the test file `non_voter_restart.rs`.

# Solution

When initializing a raft node, make it a NonVoter when there is log in store and it is not a member.

### CODE REVIEW

**Comment by battila7** [comment]
@drmingdrmer 
Hey,

I haven't carefully reviewed your fix yet, however, I believe the bug is connected with another fix: #107 

Merging #107 and modifying `main` to use `set_target_state` as follows:

~~~~Rust
        if is_only_configured_member && self.last_log_index != u64::min_value() {
            self.set_target_state(State::Leader);
        }
        // Else if there are other members, that can only mean that state was recovered. Become follower.
        // Here we use a 30 second overhead on the initial next_election_timeout. This is because we need
        // to ensure that restarted nodes don't disrupt a stable cluster by timing out and driving up their
        // term before network communication is established.
        else if !is_only_configured_member {
            self.set_target_state(State::Follower);
            let inst = Instant::now()
                + Duration::from_secs(30)
                + Duration::from_millis(self.config.new_rand_election_timeout());
            self.next_election_timeout = Some(inst);
        }
        // Else, for any other condition, stay non-voter.
        else {
            self.set_target_state(State::NonVoter);
        }
~~~~

also makes your test case pass and fixes this issue with smaller changes and no "impossible" match arms.

**Comment by drmingdrmer** [comment]
@battila7 Yes I had a look at #107 and am quite sure it fixes this issue. 
In #107 it is not clear why a decided role Follower is converted to a NonVoter. `set_target_state()` is a patch for the caller's mistake: It allows a wrong state to pass in it and then fix it. A fix at the point where the problem emits would be better.

By the way, the original code lacks 3 branches, as I marked with `// impossible` in the comments. Maybe in the future, these branches should be marked as `panic!()` to prevent a spreading error.

**Comment by battila7** [comment]
@drmingdrmer Thanks for the explanation! Yeah, the conditional in `set_target_state` indeed has a hacky feeling, something that is not the best for a dumb setter.

Also, it's great, that you've find this issue, it could've cause some real problems.

**Comment by thedodd** [comment]
@drmingdrmer thanks for the contribution here. I've merged a few other PRs recently, one of which you referenced above (#107). I'll start a review on this code now.

> is a patch for the caller's mistake: It allows a wrong state to pass in it and then fix it

That is partially true. The intent was not to "fix" a caller's mistake, but rather to reduce boilerplate, as the condition would need to be checked a bit more often if not checked there. I'm tempted to say that we should keep it as-is instead of refactoring other code (the calling code), as it helps to better encapsulate the conditional nature of the state update. @drmingdrmer @battila7 thoughts?

**Comment by thedodd** [comment]
@drmingdrmer I just took a gander at what you folks are building over there at datafuse. I would love to hear from you as far as how the API for this crate might be improved, simplified &c. Any and all feedback is welcome.

I'm going to merge this, update the changelog, and then cut a `v0.6.1` release.

**Comment by drmingdrmer** [comment]
> > is a patch for the caller's mistake: It allows a wrong state to pass in it and then fix it
> 
> That is partially true. The intent was not to "fix" a caller's mistake, but rather to reduce boilerplate, as the condition would need to be checked a bit more often if not checked there. I'm tempted to say that we should keep it as-is instead of refactoring other code (the calling code), as it helps to better encapsulate the conditional nature of the state update. @drmingdrmer @battila7 thoughts?

@thedodd 
I am not sure whether there is a chance the caller need to set a Follower that is not in members. Although very unlikely.
Everything else is all right for me:DDD.

---

It has been smooth using `async-raft` in my project. In datafuse a raft group acts as the metadata center: typically 5 candidates and many non-voters. A non-voter node just replicates logs and acts as metadata cache on every server.

In this version, a server needs to set up the replication from leader to non-voters once a leader is established because non-voter list are not persisted on disk.

My question is, would it be OK to save all the non-voters on disk, as part of the `membership`?

Any advice would be appreciated.

**Comment by battila7** [comment]
@thedodd 
I'm fine with the changes, and greatly appreciate the work you two did on this PR! Thanks!

@drmingdrmer 
In my opinion, there should definitely be some mechanism for retaining non-voters. In the current version, once a new leader is established, non-voter streams have to be restarted, right? So, there must be some way to propagate and preserve Non-Voters across the cluster. I actually listed this in #113 as something to work on, as it's crucial for our use-case
Extending `membership` seems to be the right way to go, at first glance.

**Pull request merged**
