### PR TITLE
Replace joint consensus with single node operations

### PR DESCRIPTION
**Pull request by battila7**
Hi @thedodd,

I took the initiative, and removed the joint consensus from the library, while adding the equivalents of the **AddServer** and **RemoveServer** RPCs. Also, added an RPC to remove Non-Voters.

My issue, discussed in #112 was caused by not updating properly the `self.nodes` BTreeMap during membership changes. Newly added nodes were not placed into this map, and thus, the existing removal machinery could not terminate replication for them. However, instead of fixing the joint consensus code, I thought that it would be of much more use, if I implemented **AddServer** and **RemoveServer**.

I tested the modifications in my own application and they're working correctly. Also, I updated the `stepdown.rs` test case, so you can see the changes in action.

Stuff that's still left to do:

  * [x] Guide and code documentation updates.
  * [x] Update existing test cases.
  * [x] Add new test cases for the Non-Voter related functionality.
  * [ ] Timeout for the CatchingUp consensus state.
  * [ ] Continuation of Non-Voter replication streams on leader changes.

I opened this one as a draft PR, so you can check the changes as they progress.

### CODE REVIEW

**Comment by battila7** [comment]
All tests are green now 🚀 💚

**Comment by thedodd** [comment]
@battila7 awesome! I'm really stoked to see a deep contribution like this! And I think overall moving to the updated version of config change protocol will be a great improvement.

I will do my best to review this ASAP! Definitely let me know if you have any questions as you go.

**Comment by battila7** [comment]
@thedodd Thanks for the quick reply, I'm glad that I can help with moving the library forward.

**Continuation of Non-Voter replication streams on leader changes.**
If I'm not mistaken, both the version with joint consensus and this one "drop" Non-Voters on leader election ie. the newly elected leader does not know about the Non-Voters of the old leader. What would be the best solution for this issue in your opinion?

**Timeout for the CatchingUp consensus state.**
As per the Raft spec, we should only spend a limited amount of time waiting for a non-synced node to catch up. The dissertation suggests a dynamic, round-based algorithm (§4.2.1). As I'm not 100% familiar with the codebase yet, that one looks a bit hard for me as of now. For the time being, what do you think, would a simple fixed timeout based solution suffice?

Also, I know, that while syncing a node (for which syncing was requested through `add_voter` instead of `add_non_voter`), we should provide the option for adding other, already synced nodes. However, in my opinion that would have made the implementation more complex and overall, the membership change more error-prone. Of course, let me know, if you do not think so.

Looking forward to your review, hopefully, I did not mess up that much 😄

**Comment by battila7** [comment]
Updated both the guide and the doc comments in the code.

**Comment by battila7** [comment]
Added two test cases:

  * adding a Non-Voter and checking whether it actually receives updates,
  * adding and then removing a Non-Voter and checking whether its replication stream has been cancelled.

**Comment by imrefazekas** [comment]
Any update on this? That PR looks promising... 
Or a fork available?

**Comment by thedodd** [comment]
@imrefazekas I have not started review on this PR quite yet. My plan was to wait until @battila7 gives me the word that it is ready for review. Regardless, you can just point to the branch on his fork and use it that way.

Also, the membership system currently works using the original Raft joint consensus system. So ... this is really a simplification of membership change using the latest spec recommendation.

**Comment by battila7** [comment]
@thedodd I'm on it, currently working on the config change cancellation (if the node is not able to catch up, then we should not wait indefinitely for it).

However, if I'm not mistaken, there are two bugs in the implementation of replication:

  * According to the Raft spec (see *Volatile state on leaders*), `matchIndex` should be initialized with `0`. In the current implementation, it is set to `last_log_index` however: https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L153
  * You can add dead nodes as voting members. Let me explain:
    1. Request the addition a new node, but make sure, that it's not reachable.
    1. The leader will spawn a replication stream for it, setting `next_index` to `last_log_index + 1` (https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L152) as in the Raft spec.
    1. The replication is kicked off with a `send_append_entries` call. Ideally, this call would update the `next_index` of the stream to the proper value. However, if we're unable to reach the node, then we will time out (https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L213).
    1. Therefore, we `return` from this method without updating `next_index`, leaving its value set to `last_log_index + 1`.
    1. Replication streams, by default, are created in `LaggingState`. Thus, execution will proceed to `LaggingState.run`.  
    1. In this method, we check if we're up to speed by calling `is_up_to_speed` in each iteration of the loop (https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L622). `is_up_to_speed` is implemented as `self.core.next_index > self.core.commit_index`.
    1. Since `next_index` was set to `last_log_index + 1`, `is_up_to_speed` will return `true`.
    1. Therefore, we exit `LaggingState` and enter `LineRateState`. (https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L623).
    1. Entering `LineRateState` issues a `RateUpdateEvent` (https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L521).
    1. In `handle_rate_update`, if the node is at line rate, then it is considered to be ready to join (https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/replication.rs#L68).
    1. Therefore, we continue with the membership change process even though the node is not ready to join (https://github.com/async-raft/async-raft/blob/master/async-raft/src/core/replication.rs#L81).

**Comment by drmingdrmer** [comment]
@battila7 Joint consensus should be kept. Adding/Removing one server without further constraint is buggy. See https://groups.google.com/g/raft-dev/c/t4xj6dJTP6E/m/d2D9LrWRza8J

A correct single-step member change is at least the same complicated as joint consensus.
One of the ways to make it correct is as the raft author mentioned:
> In a typical Raft implementation, a leader appends a no-op entry to the log when it is elected. This change would mean rejecting or delaying membership change requests until the no-op entry is committed.


Another issue with single-step algo is that in a cross data center deploy, the availability is reduced with single-step algo. As joint consensus works well in this scenario: initially, with a cluster of 3 raft nodes(R1,R2,R3) in 3 data center:

```
 R1     R2      R3
(R4)
DC-1   DC-2    DC-3
```

To replace R1 with R4, one-step algo adds R4 first. Before removing R1, the quorum of this 4 node cluster is at least 3 nodes. 
Thus if DC-1 is down. the cluster won't be able to elect a leader.

But with joint consensus, i.e., the quorum is `quorum_of(R1,R2,R3) ∪ quorum_of(R4,R2,R3)`(`R2,R3` is a quorum, `R1,R4,R2` is also a quorum), any two of the three data center is enough to elect a leader.

**Pull request closed without merging**
