### PR TITLE
fix off-by-one error in replication process

### LINKED ISSUE #73: Bug with get_log_entries function
The current prototype for the `get_log_entries` is `get_log_entries(&self, start: u64, stop: u64)` where start and stop are the bounds of an excluded upper bound interval. In the `MemStore` implementation,  you can notice that it is translated into a [range](https://doc.rust-lang.org/std/ops/struct.Range.html): [here](https://github.com/async-raft/async-raft/blob/master/memstore/src/lib.rs#L193). Turns out that when start = stop, `MemStore` returns an empty vec with this implementation. This becomes problematic because the replication module, [here](https://github.com/async-raft/async-raft/blob/master/async-raft/src/replication/mod.rs#L259) calls it with start = stop, which returns nothing, and triggers a snapshot.

I have encountered this bug when implementing raft for myself, with the same reasoning as the one in `MemStore`. Now, the fix is straightforward in MemStore, but I'd like to suggest that we change the prototype of `get_log_entries` to `get_log_entries<R: RangeBounds<u64>>(&self, range: T)`. This would, in my sense, dismiss any ambiguities.

I have branch with both solution implemented locally, I can make a PR with whichever solution is preferred.

### PR DESCRIPTION
**Pull request by MarinPostma**
close #73

### CODE REVIEW

**Comment by thedodd** [comment]
@MarinPostma awesome! Ping me for review once you've got these CI issues pinned down (looks like just some simple linter / clippy issues), then I'll look into getting it reviewed, merged & released!

**Comment by thedodd** [comment]
@MarinPostma also, do you mind just adding a line to the changelog describing the issue? That would be super helpful `:)`

**Comment by MarinPostma** [comment]
@thedodd It should be OK now :)
Could you make a hotfix release with this bug fix please :)

**Review by thedodd — APPROVED** [review]
+1 excellent! Thanks @MarinPostma!

**Comment by thedodd** [comment]
@MarinPostma yup! I'll get a hotfix cut ASAP. If you need this NOW now, you can always update your Cargo.toml version to point to this github repo on the master branch.

**Pull request merged**
