### PR TITLE
Update Clippy CI

### PR DESCRIPTION
**Pull request by xu-cheng**
- Use https://github.com/actions-rs/clippy-check action for better reporting.
- Run clippy with latest stable Rust instead of old version
- Run clippy against all targets including test cases
 
Example of clippy result: https://github.com/xu-cheng/async-raft/runs/1604064699

### CODE REVIEW

**Comment by xu-cheng** [comment]
The CI will pass after https://github.com/async-raft/async-raft/pull/96 is applied.

**Review by thedodd — CHANGES_REQUESTED** [review]
Hey boss. The reason for the old compiler version is because of #68. Basically there was a regression in rustc 1.46 and it was causing problems. We reverted to 1.45.2 which was not presenting the issue. We should be totally fine to just update all of CI back to the latest stable. I would prefer to do that.

I like refactoring the clippy invocations into a standalone step. Let's move that to the top of the jobs list and make it so that it must finish successfully first before the other build stages. Let me know if you would like for me to send a link over to the GHA docs on how to do that, but I think we actually have examples of how to do that in the release workflow.

Thoughts?

**Comment by xu-cheng** [comment]
I updated the PR to use stable rust for CI jobs.

> I like refactoring the clippy invocations into a standalone step.

It is already this case.

> Let's move that to the top of the jobs list and make it so that it must finish successfully first before the other build stages. 

I don't think this is a good idea. Currently, the clippy job and build jobs are running independently and in parallel. This allows CI catching more problems in one run. A failed clippy would still mean failed CI status. This is generally a better practice IMO.

**Comment by xu-cheng** [comment]
Also, would it be possible to merge #96 so the clippy job would be success.

**Comment by thedodd** [comment]
Thanks @xu-cheng!

**Pull request merged**
