### PR TITLE
Setup clippy integration.

### PR DESCRIPTION
**Pull request by PsiACE**
- Good news: clippy is now integrated.
- Bad news: CI got some errors, so it could not pass.

Close: #39

### CODE REVIEW

**Comment by PsiACE** [comment]
Check https://github.com/PsiACE/async-raft/runs/997719670 for more information.

**Comment by thedodd** [comment]
Hey there @PsiACE, sorry for the late response. Would you mind rebasing this branch onto the latest changes from master. Doing so should allow CI to be executed and made visible here on this PR.

Also, thanks for knocking this out mate! We should be able to get this merged soon. Whatever the clippy errors are, I can address them once we merge (I'll use admin privs to bypass PR gate).

**Comment by PsiACE** [comment]
Hi, @thedodd . Glad to see your reply, it is currently based on the latest `master` branch, you can merge it.

**Comment by thedodd** [comment]
Sweet! Damn near all of them were `needlessly taken reference of both operands` warnings. I'll get this merged and will get the warnings fixed soon. Thanks again!

**Pull request merged**
